# Generated by Django 4.1 on 2024-01-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='Registration',
        ),
    ]
