# Generated by Django 4.1 on 2024-01-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_registration_regnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='RegNum',
            field=models.TextField(default=100),
        ),
    ]
