# Generated by Django 4.1 on 2024-01-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_registration_regnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='RegNum',
            new_name='PhnNum',
        ),
    ]
