# Generated by Django 4.1 on 2024-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_regnum_registration_phnnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Otp',
            field=models.TextField(default=100),
        ),
    ]
